PokemonGo.RocketAPI/Client.cs
Will auto save the last player coordination in Coords.txt file
=> Added "Save last coordination function"

PokemonGo.RocketAPI.Logic/Logic.cs
Should stop  bot wasting berries on trash cp pokemons
=> Added logic to use berry only when pokemon CP is over 400 

PokemonGo.RocketAPI.Logic/Logic.cs
As XP rolls in, have the title bar update.
=> Update title bar with latest exp in real-time

PokemonGo.RocketAPI.Logic/Inventory.cs, PokemonGo.RocketAPI.Logic/Logic.cs, PokemonGo.RocketAPI.Logic/Navigation.cs, PokemonGo.RocketAPI.Logic/PokemonGo.RocketAPI.Logic.csproj, PokemonGo.RocketAPI.Logic/Utils/LocationUtils.cs
*Navigation logic is now using microsoft library for location.
*Now caching inventory for 30 seconds.(this was being called waaaay too often). 
GetBestBall() was fetching the whole inventory 4x in a row...
=> Cleaned up navigation logic. Cached inventory requests

PokemonGo.RocketAPI.Logic/Inventory.cs, PokemonGo.RocketAPI.Logic/Logic.cs, PokemonGo.RocketAPI/GeneratedCode/Payloads.cs, PokemonGo.RocketAPI/PokemonGo.RocketAPI.csproj, PokemonGo.RocketAPI/PokemonInfo.cs, PokemonGo.RocketAPI/Proto/Payloads.proto
The CalculatePokemonPerfection function now calculates the perfect MaxCP
percentage based on BaseStats. I also had to fix the protocol to change
the cpMulitplier values from int to float values
=> Added PokemonInfo to API for BaseStats,Level,MaxCP,Perfection. Fixed proto for cpMultipliers(int->float)

PokemonGo.RocketAPI.Console/App.config, PokemonGo.RocketAPI.Console/Settings.cs, PokemonGo.RocketAPI.Console/UserSettings.Designer.cs, PokemonGo.RocketAPI.Console/UserSettings.settings, PokemonGo.RocketAPI.Logic/Logic.cs, PokemonGo.RocketAPI.Logic/Navigation.cs, PokemonGo.RocketAPI/ISettings.cs
Removed Delay Between movement. This delay was created as a delay between pokestop teleports, there is no need for this now since we have humanwalking.
Added Delay between pokemon catches, as setting, defaults to 5.
Removed unnecessary call to executecatchallnearbypokemon when a pokestop is reached. This already gets called by the humanwalking when we reach the pokestop.
=> Removed Delay Between movement, Added delay between pokemon catches, CatchWhileWalking Fix

PokemonGo.RocketAPI.Console/Settings.cs
I'm not sure why it was hard coded not to catch pidgeys and rattatas, but now you can manage those settings from the "ConfigPokemonsNotToCatch.txt" file. Pidgey and rattata are no longer blocked.
=> Replaced hardcoded pokemon not to catch with text file list.

PokemonGo.RocketAPI.Logic/Logic.cs, PokemonGo.RocketAPI/Client.cs
added a check for the coordinates to ensure that the latitude is with
-90 & 90 and the longitude within -180 & 180.
Also add stardust to the title.
=> check if cords are out of bounds & add stardust to the console title

PokemonGo.RocketAPI.Logic/Logic.cs, PokemonGo.RocketAPI.Logic/Utils/Statistics.cs
The statistics 'improvement' removed the player title from the window so people running multiple bots at once can't tell which is which.
=> Add back the playername to the window title

PokemonGo.RocketAPI.Console/ConsoleLogger.cs
A previous pull overwrote this, resubmit (Magenta would be used twice otherwise).
=> berry color update

PokemonGo.RocketAPI/GeneratedCode/Payloads.cs
When you go to a stop and would be awarded an egg (but happen to have a full basket of eggs), I would get a "specified cast is not valid" error and the bot aborts.
When I simplified this line (in Visual Studio it pointed out an error after tracking it down), it continues to run but no longer freezes.
=> Fix "specified cast is not valid" error

PokemonGo.RocketAPI.Logic/Logic.cs
Fixed info regarding pokestop distance output, to be printed before we start walking, rather than when we reach the pokestop.
=> Fixed info regarding pokestop distance output timing.

PokemonGo.RocketAPI.Logic/Logic.cs
KeepMinCP can be found not in the Inventory.cs Query.
Checking for KeepMinIVPercentage is bad, because it keeps CP 10 Pokemons when they have a MinIV
Will search for a better KeepMinIVPercentage later..
=> Update Logic.cs // Change KeepMinCP Part II

PokemonGo.RocketAPI.Logic/Utils/Statistics.cs
We dont need decimal numbers for EXP/H and P/H.
Or can we catch a half pokemon? O.o
=> Update Statistics.cs // removed decimal numbers for EXP/H and P/H

PokemonGo.RocketAPI.Logic/Logic.cs
A few users were confused when the program would endlessly list their highest Pokemon. This should hopefully fix that.
=> Improved handling for some edge cases with the maximum radius feature

PokemonGo.RocketAPI.Logic/Logic.cs
Items/pokemon will only be evolved/transferred once every 5 stops.
Planning on adding a config option and a check to see if the bag is full at a later time.
=> Pokemon are evolved before being transferred, and transfer less often

PokemonGo.RocketAPI.Logic/Inventory.cs, PokemonGo.RocketAPI.Logic/Logic.cs
Updated the logger to output "best" based on your setting. The logger was still printing best based on CP and if you have IV > CP set it will show incorrect selection for best.
=> Fixed logging when using IV > CP.

PokemonGo.RocketAPI.Logic/Logic.cs
=> Better pokeball choosing

PokemonGo.RocketAPI.Console/Settings.cs
I know this should go to develop, but this is kinda a showstopper bug.
If the TryParse succeeds, it puts the value into itemAmount and returns true. If it returns true, it catches the If and so puts the itemAmount to 100. This can cause your inventory to get full and you can't recycle.
=> Fix recycling

PokemonGo.RocketAPI.Logic/Logic.cs
When using a berry the cached inventory was not being updated with the new decremented value.
=> Fix: Decrement cached berry inventory count when using a berry

PoGo.NecroBot.Logic/Navigation.cs, PoGo.NecroBot.Logic/Tasks/FarmPokestopsGPXTask.cs
GPX files weren't working with regional settings not using . as decimal seperator.
Thus, I have added CultureInfo.InvariantCulture to all Convert.ToDouble calls related to GPX.
=> Use InvariantCulture to parse GPX values

PoGo.NecroBot.Logic/Inventory.cs, PoGo.NecroBot.Logic/Tasks/TransferDuplicatePokemonTask.cs
Made it possible to transfer Pokemon when you have only one of this type left.
Fixes an error when you wanted to transfer your best Pokemon(last one).
(In case you only want Pokemons reaching your criterion)
=> KeepMinDuplicatePokemon can now be set to zero

PoGo.NecroBot.CLI/App.config, PoGo.NecroBot.CLI/Settings.cs, PoGo.NecroBot.CLI/UserSettings.Designer.cs, PoGo.NecroBot.CLI/UserSettings.settings, PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Inventory.cs, PoGo.NecroBot.Logic/Tasks/TransferDuplicatePokemonTask.cs, PoGo.NecroBot.Logic/Utils/Statistics.cs
With KeepPokemonsThatCanEvolve=true it also kept all pokemons that couldn't evolve. Added KeepPokemonsThatCanEvolve to Settings
=> Fixed a logic error in GetDuplicatePokemonToTransfer & reduced size of GetXpDiff

PoGo.NecroBot.Logic/Inventory.cs
I still prefer my oneliner
`if (settings.CandyToEvolve > 0 && familyCandy.Candy / settings.CandyToEvolve > amountToSkip)
amountToSkip = familyCandy.Candy / settings.CandyToEvolve;`
up to you which one you want to implement.
=> Fixed divide by zero in GetDuplicatePokemonToTransfer

PoGo.NecroBot.Logic/Inventory.cs
Currently KeepMinIvPercentage is only being used in the UseBerry logic and I have added it in for the transfer duplicates. Now iit will keep pokemon >= 85 or pokemon >= 1000; [Values specified by your settings.]
I also added keeping of pokemon with 100% IV because some players were complaining about losing their 2nd 100% Eevee.
=> Fixed KeepMinIvPercentage's usage

PoGo.NecroBot.CLI/Program.cs, PoGo.NecroBot.CLI/Settings.cs
Reverts NecronomiconCoding/NecroBot#581
=> Revert "Give json settings the touch"

PoGo.NecroBot.CLI/ConsoleEventListener.cs, PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj, PoGo.NecroBot.CLI/Settings.cs, PoGo.NecroBot.Logic/Event/DisplayHighestsPokemonEvent.cs, PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj, PoGo.NecroBot.Logic/State/InfoState.cs, PoGo.NecroBot.Logic/State/LoginState.cs, PoGo.NecroBot.Logic/StatisticsAggregator.cs, PoGo.NecroBot.Logic/Tasks/LogBestPokemonTask.cs
As some people request I added this functionality again to display your stronger pokemon!
#553
=> Display your strong Pokemon

PoGo.NecroBot.CLI/Program.cs, PoGo.NecroBot.CLI/Settings.cs, PoGo.NecroBot.Logic/Logging/Logger.cs
`cli.exe <Profile>`
if no parameter is given, the standard paths are beeing used.
if Profile is set, it will use configs/logs from _CurrentDir\<Profile>\_
any path specific functions should use **GlobalSettings.ProfilePath** and
**GlobalSettings.ConfigPath**
=> Added MultiProfile via CommandLine parameter

PoGo.NecroBot.CLI/ConsoleEventListener.cs, PoGo.NecroBot.CLI/Settings.cs, PoGo.NecroBot.Logic/Common/Translations.cs, PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj, PoGo.NecroBot.Logic/State/Context.cs, PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs, PoGo.NecroBot.Logic/packages.config
+ added settings entry to set the language code for the language file you would like to use
=> Added support for translations, customizing messages to your desire

PoGo.NecroBot.CLI/ConsoleEventListener.cs, PoGo.NecroBot.CLI/Settings.cs, PoGo.NecroBot.Logic/Event/EggIncubatorStatusEvent.cs, PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Inventory.cs, PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj, PoGo.NecroBot.Logic/State/FarmState.cs, PoGo.NecroBot.Logic/Tasks/UseIncubatorsTask.cs
Automatic use of egg incubators before every farming run, with setting for enabling (default=on).
Currently not executed in-between pokestops, but that would be a good next step. Simply add up the distances between stops and when enough of a distance (1km+) has been traveled, check incubators.
=> Egg incubation

PoGo.NecroBot.CLI/Settings.cs, PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs
Ensures that a minimum number of pokemon are ready to be evolved before using a lucky egg. See #632
=> Add configurable minimum number of evolvable pokemon for lucky egg usage

PoGo.NecroBot.CLI/ConsoleLogger.cs, PoGo.NecroBot.Logic/Common/Translations.cs, PoGo.NecroBot.Logic/Navigation.cs, PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj, PoGo.NecroBot.Logic/State/VersionCheckState.cs, PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs, PoGo.NecroBot.Logic/Utils/LocationUtils.cs, PoGo.NecroBot.Logic/packages.config
I fixed some problems which prevented the bot from running properly on mono/Linux.
Changes:
- replace `System.Device.Location.GeoCoordinate` with `GeoCoordinatePortable.GeoCoordinate` (nuget package), because `System.Device.Location` assembly ist not available on mono/Linux
- replace hard coded paths with calls to `Path.Combine()`
- change `Console.OutputEncoding` to UTF8
=> Fix mono/Linux compatibility

PoGo.NecroBot.CLI/Program.cs, PoGo.NecroBot.CLI/Settings.cs, PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Inventory.cs, PoGo.NecroBot.Logic/Tasks/TransferDuplicatePokemonTask.cs
I accidently overwrote (and autoclosed) my previous PR about the MultiProfile fix: https://github.com/NecronomiconCoding/NecroBot/pull/749
So this contains the multiprofile fixes and a brand new feature to use individual transfer filter minimum values for each pokemon.
Example config:
`"PokemonsTransferFilter": {
"Pidgeotto": {
"KeepMinCp": 1500,
"KeepMinIvPercentage": 90.0,
"KeepMinDuplicatePokemon": 1
},
"Fearow": {
"KeepMinCp": 1500,
"KeepMinIvPercentage": 90.0,
"KeepMinDuplicatePokemon": 2
}
},`
This comes in handy if you want to transfer all the useless pidgeottos and golbats that are over your default CP limit. Or if you want to keep eevees with 600 cp which is under a cp limit of 1000. For all the pokemons not in this list it will use the default Min settings.
MultiProfile …
=> MultiProfiles fix & Individual transfer filter feature

PoGo.NecroBot.Logic/State/FarmState.cs, PoGo.NecroBot.Logic/Tasks/FarmPokestopsGPXTask.cs, PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs
Wrapped RenamePokemonTask in a IF block to check if RenameAboveIV settings is set to true before executing RenamePokemon Task
Added RenamePokemonTask  to FarmPokestopsGPXTask.cs
Moved RenamePokemonTask to after evolving and transfering in FarmState.cs, FarmPokestopsTask.cs and FarmPokestopsGPXTask.cs
=> Fix: Move RenamePokemonTask to after evolving and transferring

PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
Was broken from fix for #489. Updated to use Current instead of Default Lat/Long.
=> Fix for trying to get nearby pokestops when using GPX. 

PoGo.NecroBot.Logic/Inventory.cs, PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs
EvolveAllPokemonAboveIv and EvolveAllPokemonWithEnoughCandy configs share the same task yet do not properly differentiate between the two in the logic.
The logic is now as follows:
If EvolveAllPokemonWithEnoughCandy only true, then it will evolve all in PokemonsToEvolve list.
If EvolveAllPokemonAboveIv only true, then only those above the threshold will be evolved.
If both, evolves all in list and those above the threshold.
This should resolve #810 and #816.
I have also implemented #763, where an empty PokemonsToEvolve list evolves all eligible pokemon.
=> Fix evolution logic

PoGo.NecroBot.Logic/PoGoUtils/PokemonInfo.cs
I am not sure if this is the right place to put this / type it.
But these will be helpful later when MAYBE  a logic for trasnfer after it check what moves the pokemon has.. 
for each pokemon i took the best combo and grabbed the id's of these moves from the protos. 
again, no idea if it's pushed in the right spot/written the write way. whats important there is the data that does not exist currently in necro.
=> Pokemon Moves

PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs
Bug Fix: softban detection was incrementing TimesZeroXPawarded when Experience was Awarded , instead needs to be when NOT awarded experience.
=> Bug Fix: softban detection was incrementing TimesZeroXPawarded incorrectly 

PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs
Bug Fix: FortUsedEvent was only firing when TimesZeroXPawarded was greater than 5 instead should fire when less than or equal to 5
=> Bug Fix: FortUsedEvent needs to be called when TimesZeroXPawarded <= 5 not greater than

PoGo.NecroBot.CLI/Config/Translations/translation.no.json
=> Update Translating - Norwegian

PoGo.NecroBot.CLI/ConsoleEventListener.cs, PoGo.NecroBot.Logic/Common/Translations.cs, PoGo.NecroBot.Logic/Event/EggHatchedEvent.cs, PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj, PoGo.NecroBot.Logic/Tasks/FarmPokestopsGPXTask.cs, PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs, PoGo.NecroBot.Logic/Tasks/UseIncubatorsTask.cs
**Edit: See new comment below**
Still doesn't log hatch-events though, since `ctx.Client.Inventory.GetHatchedEgg();` doesn't seem to return anything. Perhaps because the inventory (which includes pokemon) has already been refreshed?
=> Egg incubation checks during PokeStop farming, and logging for hatch-events

PoGo.NecroBot.Logic/Common/Translations.cs, PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Settings.cs, PoGo.NecroBot.Logic/State/Session.cs
Rearranged Settings for better overview in the config.json
Fixed conflicts from
https://github.com/NecronomiconCoding/NecroBot/pull/1083
Worked this out together with Ilses so he should be fine with it. Credits to him for most of the code.
Config paths should now be access via
`ctx.LogicSettings.ProfilePath` _\Release\Profile\_
`ctx.LogicSettings.ProfileConfigPath` _\Release\Profile\Config\_
`ctx.LogicSettings.GeneralConfigPath` _\Release\Config\_
=> Settings rearrange & added config paths

PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj, PoGo.NecroBot.Logic/Settings.cs, PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs, PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs, PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs, PoGo.NecroBot.Logic/Tasks/RecycleItemsTask.cs, PoGo.NecroBot.Logic/Tasks/RenamePokemonTask.cs, PoGo.NecroBot.Logic/Tasks/TransferDuplicatePokemonTask.cs, PoGo.NecroBot.Logic/Utils/DelayingUtils.cs
FEATURE: randomized delay between each action
DelayBetweenPlayerActions (Value)
Delay in miliseconds between any actions (such as attempt to catch a
pokemon, evolving a pokemon, farming a pokestop, recycling an itep etc).
This value is randomized between + and - 30% of given value after each
action. If set to 0, default delays are applied (for some of the
actions).
=> FEATURE: randomized delay between each action

PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs
LuckyEgg existence should be checked before "UseLuckyEggsMinPokemonAmount" condition to be able to bypass it.
If there is no LuckyEgg in inventory, there is also no need to check "pokemonToEvolve.Count" value. It should just evolve the pokemon.
=> [FIX] For Evolution Logic with LuckyEggs

PoGo.NecroBot.CLI/ConsoleEventListener.cs, PoGo.NecroBot.Logic/Common/Translations.cs, PoGo.NecroBot.Logic/Event/SnipeScanEvent.cs, PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj, PoGo.NecroBot.Logic/Settings.cs, PoGo.NecroBot.Logic/Tasks/FarmPokestopsGPXTask.cs, PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs, PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
Feature will work with the rest of the logic every 5 Pokestops to snipe configured areas for Pokemon. May need some updates for data calls sine I'm relying on an external API call to determine spawns.
Utilizes two new settings:
bool: SnipeAtPokestops
List<SnipeSettings>: PokemonToSnipe
Example:
"PokemonToSnipe": [
{
"Locations": [
{
"Latitude": 38.556807486461118,
"Longitude": -121.2383794784546
}
],
"Pokemon": "Dratini"
}
]
=> [Feature] Configurable Pokemon Sniping

PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
Due to the sleep in here this function can delay the walk to a pokestop up to (pokemons around you) * 3 sec. Not sure if it's worth to implement the calls. A check for EventNoPokeballs after the EncounterPokemon with a loop break might be better even though it's after the sleep.
=> Improved bottleneck when run out of pokeballs

PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Settings.cs, PoGo.NecroBot.Logic/Tasks/RenamePokemonTask.cs
allow to set custom template string for renaming function
example:
```json
"RenameTemplate": "{0}_{1}"
```
will output: Zubat_95
```json
"RenameTemplate": "[{1}]{0}"
```
output: [95]Zubat
{0} - Pokemon name
{1} - IV
I've spend some more time on this and figured out there was an unreachable block of code (since this task only runs if **RenameAboveIv** is true) and fixed a bug with empty name
Also now it's possible to rename Pokemons to their original name just by setting template to `"{0}"`
with IV:
original:
=> setting up template for renaming function

PoGo.NecroBot.CLI/Program.cs, PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Settings.cs, PoGo.NecroBot.Logic/Tasks/FarmPokestopsGPXTask.cs, PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs, PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
See for yourself: [Image](https://dl.dropboxusercontent.com/u/28069358/wow.jpg)
The client connects to an open source server made by @Ilses and me:
https://github.com/5andr0/PogoLocationFeeder/tree/master/PogoLocationFeeder
Right now it is crawling new pokemon locations from the discord channel #sniping 
and sending them via json to the client. This can be improved to be a pokevision scraper etc
```
"SnipeAtPokestops": true,
"SnipeLocationServer": "localhost",
"SnipeLocationServerPort": 16969,
"UseSnipeLocationServer": true,
"UseTransferIVForSnipe": false,
"MinDelayBetweenSnipes": 20000,
```
There's a major bug in FarmPokestopsGPXTask.cs
where `while (pokestopList.Any())` is never true because pokestops are already @ cooldown because of UseNearbyPokestopsTask. So all the calls in the loop …
=> Sniper with automated pokelocation feed

PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
Set snipe timeout to avoid waste of time, especially when network is unstable.
=> Set snipe timeout to avoid waste of time.

PoGo.NecroBot.CLI/Program.cs
Since many sites like PokeVision rely on coordinates and other decimals
being seperated with dots and not with comma. For example, coordinates
have to be 41.242 and not 41,242.
Many non-us locales do use a comma for those separations. This commit
sets the locale for the program fixed to en-US which solves the problem.
Signed-off-by: Lyrex <admin@lyrex.net>
=> Fix coordinate related things (i.e. sniping) for non-us users

PoGo.NecroBot.Logic/Settings.cs
Optimized default RenameTemplate "{0}_{1}"; to "{1}_{0}" 
With this config you can sort your Pokemons with A-Z to sort your pokemons by IV
=> Optimized default RenameTemplate setting

PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
Fixed Sniping and made a small readability refactoring. Seems like pokevision changed the json and removed the is_alive entry.
Sample json i got:
"{"
status":"success",
"pokemon":[
{"id":719183341,
"latitude":37.807812375435,
"longitude":-122.42128665472,
"pokemonId":16,
"expiration_time":1469827668
},
=> Snipe Fix, pokevision api changed.

PoGo.NecroBot.Logic/Tasks/FarmPokestopsGPXTask.cs, PoGo.NecroBot.Logic/Utils/DelayingUtils.cs
In FarmPokestopsGPXTask UseNearbyPokestopsTask clears pokestops before it retrieves new ones from `var pokestopList = await GetPokeStops(session);`
Therefore pokestopList will be empty, the `while (pokestopList.Any())` loop is never entered and all the tasks are never called.
Affected tasks have been:
```
RecycleItemsTask
SnipePokemonTask
EvolvePokemonTask
TransferDuplicatePokemonTask
RenamePokemonTask
```
=> Fixed a bug in gpx where tasks were never called

PoGo.NecroBot.Logic/PoGoUtils/PokemonInfo.cs
Calculate IV the way all IV calculators on the Internet do: ATK+STA+DEF/45*100.
I could list a countless list of IV calculators here, most of them from r/thesilphroad and r/pokemongodev and all of them use this formula.
Before the Bot was displaying sorted by IV list of pokemon on the start everyone was using 3rd party tools for calculating IV.
Everyone was wondering why so many 86-90 IV pokemons were not transfered when bot was set to transfer pokes under 90 IV.
That's exactly why, because of the weird formula is using the IV% is artificialy increased by up to 3.5%.
=> Simple IV calculation.

PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Inventory.cs, PoGo.NecroBot.Logic/Settings.cs
Hi,
i changed the recylce behaviour to throw away low level pokeballs and potions and keep the better ones. This leads to a far more frequent usage of the better pokeballs instead of throwing them away. The new setting entires configure the total amout of pokebals/potions over all types that shall be kept.
=> Throw away low level pokeballs, potions, revives and keep the better ones.

PoGo.NecroBot.CLI/FodyWeavers.xml, PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj, PoGo.NecroBot.CLI/packages.config
This would allow the bin/* folders to only contain the NecroBot executable, it's .config, and it's .pdb.
The folder would then look like this:
bin/
-- Debug/ (or Release/)
---- Configs/
---- Logs/
---- temp/
---- NecroBot.exe, .config, .pdb
Before: http://i.imgur.com/vFgZAjn.png
After: http://i.imgur.com/6eEArBw.png
The GitHub repo can be found here: https://github.com/Fody/Costura. Demonstrates some config tweaks you can make, should you want.
CREDS TO JASH ON DISCORD BECAUSE HE'S A HOE
=> cleanup VS output dir with Fody Costura

PoGo.NecroBot.Logic/Common/Translations.cs, PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Settings.cs, PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
This replaces "Fixed MinPokeballsToSnipe".
At the moment the bot stops sniping if he falls below the MinPokeballsToSnipe value. For example with "MinPokeballsToSnipe" = 100 he will stop sniping if he has 99 pokeballs left.
I don't think that was intended. With the fix he will snipe until he has MinPokeballsWhileSnipe pokeballs left and only start sniping if he has at least MinPokeballsToSnipe pokeballs.
=> Enhanced pokeball-management for sniping

PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Settings.cs, PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs
Set a max amount of pokeballs/retrys that can be used per pokemon. 0 for
no limit.
=> MaxPokeballsPerPokemon

PoGo.NecroBot.CLI/Config/Translations/translation.fr.json
Fixed missing space, incorrect plurial mode
"eventFortTargeted"
"eventPokemonTransferred"
"eventPokemonCapture"
"eventNoPokeballs"
"incubatorPuttingEgg"
"incubatorStatusUpdate"
"couldntCopyToClipboard"
"couldntCopyToClipboard2"
"coordinatesAreInvalid"
"gotUpToDateVersion"
=> Updated French language

PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj, PoGo.NecroBot.Logic/Settings.cs
Fixed version for randomized spawn location.
[#1430](https://github.com/NecronomiconCoding/NecroBot/pull/1430)
=> Offset parameter

PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Inventory.cs, PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj, PoGo.NecroBot.Logic/Settings.cs, PoGo.NecroBot.Logic/State/FarmState.cs, PoGo.NecroBot.Logic/Tasks/DisplayPokemonStatsTask.cs, PoGo.NecroBot.Logic/Tasks/Farm.cs, PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs, PoGo.NecroBot.Logic/Tasks/LevelUpPokemon.cs, PoGo.NecroBot.Logic/Tasks/LevelUpPokemonTask.cs
=> Add Upgrade Pokemon Levelling Up

PoGo.NecroBot.Logic/Properties/AssemblyInfo.cs, PoGo.NecroBot.Logic/Tasks/DisplayPokemonStatsTask.cs, PoGo.NecroBot.Logic/Tasks/RecycleItemsTask.cs
If the amount of total balls currently hold is greater than
TotalAmountOfPokebalsToKeep, the Bot will recycle poke balls from low
level balls.
In Configs, TotalAmountOfPokebalsToKeep should be less than the sum of
all separate poke balls in ItemRecycleFilter.
Now optimized recycling of potions and revives also works in latest commit.
=> Impltement optimized recycling

PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Inventory.cs, PoGo.NecroBot.Logic/Settings.cs, PoGo.NecroBot.Logic/Tasks/LevelUpPokemonTask.cs
Adds minimum stardust for levelling up pokemon so you can do more at once
=> Add minimum stardust for levelup

PoGo.NecroBot.Logic/Inventory.cs, PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj, PoGo.NecroBot.Logic/State/FarmState.cs, PoGo.NecroBot.Logic/Tasks/Farm.cs, PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs, PoGo.NecroBot.Logic/Tasks/GetPokeDexCount.cs
Add Pokedex details will display seen and caught out of 151
=> Add PokeDex

PoGo.NecroBot.CLI/ConsoleEventListener.cs, PoGo.NecroBot.Logic/Event/EvolveCountEvent.cs, PoGo.NecroBot.Logic/Properties/AssemblyInfo.cs, PoGo.NecroBot.Logic/Tasks/DisplayPokemonStatsTask.cs, PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs
Displays how many Pokemon could potentially be evolved every
EvolvePokemonTask.Execute(..)
I've found this particularly useful for seeing how close I am to the
"UseLuckyEggsMinPokemonAmount" when "UseLuckyEggsWhileEvolving"=true.
NOTE: Translation handling should be implemented at some stage. I
haven't had the time to do that (Should be handled in the
ConsoleEventListener Handler)
=> Potential Evolves Logging

PoGo.NecroBot.Logic/State/InfoState.cs
Will work even if   "AmountOfPokemonToDisplayOnStart": 0
Some people don't want to flood console with it if they can get full list from the dump.
=> DumpPokemonStats fix

PoGo.NecroBot.Logic/Settings.cs, PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
These settings would potentially be written as zeros if they didnt exist in the config:
RecycleInventoryAtUsagePercentage
WalkingSpeedInKilometerPerHour
SnipingScanOffset
DefaultAltitude
DefaultLatitude
DefaultLongitude
=> Resolved issue with default value of zero for a couple config values

PoGo.NecroBot.Logic/Common/ApiFailureStrategy.cs, PoGo.NecroBot.Logic/State/LoginState.cs
FIX PtcOfflineException and AccessTokenExpiredException get not catched
and Bot crash
=> Fix Crash  PtcOfflineException and AccessTokenExpiredException

PoGo.NecroBot.CLI/ConsoleEventListener.cs, PoGo.NecroBot.CLI/ConsoleLogger.cs, PoGo.NecroBot.CLI/Models/LoggingStrings.cs, PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
**What i have done:**
- Created Model for logging strings which can be initialized by a static method
- In the method use null propagation together with ternary operator to set the default string or the translated string
- Changed access modifiers of the constructor of the logger to internal
- Fixed indentation of xml documentation comments and normal comments to fit [official guidelines](https://msdn.microsoft.com/en-us/library/ff926074.aspx#Anchor_2)
- Added new line at end of the file
- Update Access Modifiers of the Console Event listener and change the parameter names there
=> Pull request for refactoring of the logging messages

PoGo.NecroBot.Logic/Settings.cs
Changed order for PtcUsername and PtcPassword to avoir mistake, now it's email then password.
=> Correct order for PtcUsername and PtcPassword

PoGo.NecroBot.Logic/Tasks/DisplayPokemonStatsTask.cs
The first row is the header for the columns  
There are some properties of ```PokemonData``` that I left out since they didn't seem applicable.  
The information currently dumped isn't very useful mostly due to the way it's formatted.
=> Change CSV dump to be comma seperated-values as well as output more data

PoGo.NecroBot.CLI/Config/Translations/translation.fr.json
Fixed after #1609 
Fixed "Value": "Deck Pokémon(151) : Rencontré {0} | Capturé {1}"
=> Update translation.fr for egg/incense/pokedeckcount

PoGo.NecroBot.Logic/Inventory.cs
When choosing Pokemon to transfer, if IV, then keep highest CP - if CP, keep highest IV.
=> Updating IV and CP logic for transferring.

PoGo.NecroBot.Logic/Settings.cs
Fixes for default pokeball settings for #1801
=> Fix default ball settings.

PoGo.NecroBot.CLI/Program.cs
#1884 Removed fixed console width making application unbuildable on smaller screens (console window should be set in default settings of the console itself on  user's computer)
=> [issues/1884] BUG: removed fixed console window width

PoGo.NecroBot.CLI/Program.cs
When it's waiting a long time to login, it just shows path to the exe, now it'll show NecroBot starting.
@AiksuCoding fixed conflicts
=> Set Console.Title on start

PoGo.NecroBot.CLI/ConsoleEventListener.cs, PoGo.NecroBot.Logic/Common/Translations.cs, PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Settings.cs, PoGo.NecroBot.Logic/Tasks/CatchIncensePokemonsTask.cs, PoGo.NecroBot.Logic/Tasks/CatchLurePokemonsTask.cs, PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
Fixed conflicts and reimplemented:
Ignore all pokemon not on Sniper Filter
Time for pokestop arrival
=> [Feature] Added a better config merging system

PoGo.NecroBot.Logic/Tasks/EggsListTask.cs, PoGo.NecroBot.Logic/Tasks/InventoryListTask.cs, PoGo.NecroBot.Logic/Tasks/PokemonListTask.cs
They previous delay was not consistent with settings.
=> Websocket - Add correct delay

PoGo.NecroBot.CLI/Program.cs, PoGo.NecroBot.Logic/State/PositionCheckState.cs
LastPos.ini was saved in the same location regardless of profile causing bots to constantly overwrite the other bots last position in the file. Also caused crashes when multiple bots tried to access the file at the same time.
=> Put LastPos.ini into profile directories

PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs
pls, dont break the logic of evolve behavior, analyze and test your changes before commit to master, Evolve*KEPT*PokemonsAtStorageUsagePercentage have only one certain meaning. If you want change logic then pls rename parameter to EvolvePokemonsAtStorageUsagePercentage without KEPT.
Without this check people who wants to evolve pokemon with above IV or just with enough candy, but with options KeepPokemonsThatCanEvolve = false (case with default config for new users) will never have it, and even their pokemon might be transfered instead of evolving... (sry for my bad english)
=> prevent wrong Evolve behavior, pls do n't change meaning of mnemonic parameters

PoGo.NecroBot.Logic/Tasks/UseIncubatorsTask.cs
Issue: [https://github.com/NECROBOTIO/NecroBot/issues/1579](https://github.com/NECROBOTIO/NecroBot/issues/1579)
Implemented as suggested in the issue:
The unlimited incubator will prefer long eggs if no limited incubators are available anymore.
=> changed egg prio for unlimited incubator

PoGo.NecroBot.CLI/WebSocketInterface.cs
I'm working on a web ui accessible for everyone through the browser.
however, to do that, we need either non-tls or a signed certificate.
I've added a new non-tls endpoint without deleting the old one for compatibility reason
=> add non-tls socket for webui

PoGo.NecroBot.CLI/Config/Translations/translation.de.json
Some (5) Pokémon names were misspelled in the German translation file.
explanation for the change from "NidoranF" to "NidoranW"
In German it's
Female = Weiblich = W -> NidoranW
Male = Männlich = M -> NidoranM
=> German translation correction

PoGo.NecroBot.CLI/Config/Translations/translation.ca.json, PoGo.NecroBot.CLI/Config/Translations/translation.da.json, PoGo.NecroBot.CLI/Config/Translations/translation.de.json, PoGo.NecroBot.CLI/Config/Translations/translation.es.json, PoGo.NecroBot.CLI/Config/Translations/translation.et.json, PoGo.NecroBot.CLI/Config/Translations/translation.gr.json, PoGo.NecroBot.CLI/Config/Translations/translation.hu.json, PoGo.NecroBot.CLI/Config/Translations/translation.id.json, PoGo.NecroBot.CLI/Config/Translations/translation.it.json, PoGo.NecroBot.CLI/Config/Translations/translation.lt.json, PoGo.NecroBot.CLI/Config/Translations/translation.nl.json, PoGo.NecroBot.CLI/Config/Translations/translation.no.json, PoGo.NecroBot.CLI/Config/Translations/translation.pl.json, PoGo.NecroBot.CLI/Config/Translations/translation.pt-br.json, PoGo.NecroBot.CLI/Config/Translations/translation.pt-pt.json, PoGo.NecroBot.CLI/Config/Translations/translation.ro.json, PoGo.NecroBot.CLI/Config/Translations/translation.ru_RU.json, PoGo.NecroBot.CLI/Config/Translations/translation.sv.json, PoGo.NecroBot.CLI/Config/Translations/translation.th.json, PoGo.NecroBot.CLI/Config/Translations/translation.tr.json, PoGo.NecroBot.CLI/Config/Translations/translation.uk_UA.json, PoGo.NecroBot.CLI/Config/Translations/translation.vi.json, PoGo.NecroBot.CLI/Config/Translations/translation.zh_CN.json, PoGo.NecroBot.CLI/Config/Translations/translation.zh_TW.json
Added support for "PokemonStrings" and "PokemonMovesetStrings" must have #2711 merged first.
"PokemonStrings" + "PokemonMovesetStrings" 
= da, et, gr, hu, id, it, lt, nl, no, pt-br, pt-pt, ru_RU, sv, th, tr, uk_UA, ro, ca
"PokemonMovesetStrings" only
= de, es, pl, zh_CN, vi
#2711 [Feature] Automatic Translation Detection
- "PokemonMovesetStrings" support
- based on https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Enums/PokemonMove.proto
=> Added "PokemonStrings" + "PokemonMovesetStrings" language support for #2711

KillSwitch.txt, PoGo.NecroBot.CLI/Config/Translations/translation.fr.json, PoGo.NecroBot.CLI/ConsoleEventListener.cs, PoGo.NecroBot.CLI/ConsoleLogger.cs, PoGo.NecroBot.CLI/Models/LoggingStrings.cs, PoGo.NecroBot.CLI/Program.cs, PoGo.NecroBot.Logic/Common/Translations.cs, PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Logging/Logger.cs, PoGo.NecroBot.Logic/Settings.cs, PoGo.NecroBot.Logic/State/VersionCheckState.cs, PoGo.NecroBot.Logic/StatisticsAggregator.cs, PoGo.NecroBot.Logic/Utils/ErrorHandler.cs, PoGo.NecroBot.Logic/Utils/Statistics.cs
_Resubmitted #2711 with fresh clone_
**CHANGELOG:**
- Added a new method to pull the system translation when new configs are created. It will then ask the user if they would like to enter a new language code (And then build the config)
- Now asks the user if they would like to download/install a new update (When there is one) and will display any new options added in the version.
- Implemented functions to allow for the translation of pokemon moves
- If the user is updating the bot and new options are added, ask the user if they would like to open the config file to view the new additions.
- Added a low level killswitch to disable the bot and print a notification for the reason. This is only for situations whereby the bot may be broken. **This was made extremely quickly and I believe …
=> Added multiple usability improvements

PoGo.NecroBot.Logic/Utils/LocationUtils.cs
If google have too mutch request they send notting ...
and make a crash
` System.ArgumentNullException: Value cannot be null.
Parameter name: value
at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
at PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 36
at PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 65
at PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 42 …
=> Fix for realistic height

PoGo.NecroBot.Logic/Settings.cs
change the default setting for UseBerriesOperator from AND to OR to use more berries to have more sucefull catches and less Recycling
=> Change  UseBerriesOperator  to OR for better catch

PoGo.NecroBot.CLI/ConsoleEventListener.cs
Limit pokemonCaptureEvent Latitude & Longitude to 6 decimal places in log.
=> Limit pokemon Lat & Long to 6 decimals

PoGo.NecroBot.Logic/Inventory.cs
Accounts for the candy gained when evolving, can be changed to "-2" if considering transferring the newly evolved pokemon.
=> Update Inventory.cs - Optimal Number of candies needed for mass evolve

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj, PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
The VS default path for packages is badly done -- this fixes them. Should be more friendly toward projects that build off of NecroBot internals.
=> csproj dependency dirs would break if they were moved around

PoGo.NecroBot.CLI/Program.cs, PoGo.NecroBot.CLI/Resources/ProgressBar.cs
If you try to redirect the output stream of the program and are not actually running it the program directly, you end up getting an IOException saying invalid handle and crashing the bot.
This occurs because of the use of CursorLeft and Clear console functions.
Catching the exception prevents the bot from crashing in the case that the progress bar is not able to load because the output stream is being redirected.
=> Prevent IOException from crashing bot, occurs when trying redirecting output stream

PoGo.NecroBot.CLI/ConsoleEventListener.cs
Improve text formatting with padding for known fields length in order to
improve readability of transfer log
=> Pokemon trasfer readability

PoGo.NecroBot.CLI/Resources/ProgressBar.cs
If you try to set `Console.CursorLeft` to a value greater than
`Console.WindowWidth` a
`System.ArgumentOutOfRangeException` is thrown.
Set `Console.WindowWidth` to 1 + max value used to set `Console.CursorLeft`.
=> Fix when console width is to small

PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs
Its currently only using 2 berries per pokemon when maxBerriesToUsePerPokemon is set to 3. 
If you increment your counter before you check it you need to use a less than or equal to not just less than. 
Or you can check if its less than maxBerriesTouse +1 .
=> [Fix] The check if AmountofBerries is less than MaxBerriesToUse was off by 1 . 

PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Settings.cs, PoGo.NecroBot.Logic/Tasks/RecycleItemsTask.cs
Such a rookie with Git... this should finally check out fine. Tested code and it is all hunky dory.
_Changed the random recycle from the first version to allow for users to configure it on or off, and how random it will be.
Purpose for this is to make recycling more human-like.
Example:
Pokeballs: 73
Greabballs: 49
Ultaballs: 31
Masterballs: 11
Total pokeballs = 164
TotalAmountOfPokeballsToKeep set to 120
For a human to recycle to 120, they would need to add the quantity of each of their pokeballs up and scrap accordingly. This is highly unlikely to happen, and more often than not they would just scrap a random amount of the weakest pokeballs.
The config will give an option to turn if on and off, and set the +/- randomized value to use._
=> RandomRecycle v2

PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj, PoGo.NecroBot.Logic/Settings.cs, PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs, PoGo.NecroBot.Logic/packages.config
This bypasses the cloudflare protection on Pokesnipers api.  Also introduce new config option "GetSniperInfoFromPokeSnipers": "true".  This is OR'd with the Pokezz snipers, so you can snipe from both sites at the same time, or disable one or the other as wished.
=> Add back a working Pokesnipers sniping implementation

PoGo.NecroBot.CLI/Program.cs
If a second argument is provided, it is interpreted as a set of latitude/longitude comma-delimited coordinates, which take precedence over config file value. In case they cannot be parsed to "double", they are silently ignored.
=> Added command line coordinate parsing

PoGo.NecroBot.Logic/State/FarmState.cs
So we don't rename and then transfer the same pokemon.
=> Wait for transfers to finish before renaming

PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
Fix bug with pokezz sniping where you can occasionally get an error adding new pokemon to collection when it is enumerating the list.  The socket should be closed after pokemon data is received.
Also, just to save some time and not opening another pull request for a one-line fix, I also fixed the logging for pokesnipers.com sniping to pass the IV value along.
=> Fix pokezz sniping socket bug

PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Settings.cs, PoGo.NecroBot.Logic/Tasks/RecycleItemsTask.cs
The delay between actions was removed for recycling items, causing all the actions to be performed within milliseconds of each other, essentially insta-recycling all items at once.
If they detect this, it is a huge red flag saying you are a bot. 
Here I have only added it back in, but if needed the config could have a boolean option for this to allow the user to disable the timer
=> [FIX] No Delay on Recycle

PoGo.NecroBot.CLI/ConsoleLogger.cs, PoGo.NecroBot.CLI/Program.cs, PoGo.NecroBot.Logic/Logging/Logger.cs, PoGo.NecroBot.Logic/Tasks/LevelUpPokemonTask.cs
Changed levelup colour to something different seemed to bland to be the same as the others
=> Change Level Up Colour

PoGo.NecroBot.Logic/Tasks/LevelUpPokemonTask.cs
TODO: AmountOfTimesToUpgradeLoop handling should be adjusted, too.
=> Fixe LevelUpPokemonTask to fire even when only one pokemon to upgrade

PoGo.NecroBot.CLI/Config/Translations/translation.id.json
New untranslated string (from #4124).
`Koordinat` is a place, so must be separated from `di`, @wakrad.
=> Bahasa Indonesia: fix and update translations.

PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
1. Remove redundant checks to locations visited (was checking this twice unnecessarily)
2. Remove double-addition and incorrect addition to locations visited (it would blacklist a location even if sniping did not occur due to full pokemon inventory for instance).
3. Cleanup last sniping time (should be set within the ```Snipe``` function).
By the way, this is a revert of most of the changes made in 329306bf469437827376204f923234f059f66be7
=> Bug fix - Clean up sniping logic

PoGo.NecroBot.Logic/State/VersionCheckState.cs, PoGo.NecroBot.Logic/Utils/ErrorHandler.cs
If the bot has updated, successfully transferred a config, and the user has not chosen to open the config; the bot will restart automatically.
Solves issue #3513
=> Bot now restarts when updating

PoGo.NecroBot.Logic/Navigation.cs
The call to functionExecutedWhileWalking() was missing for teleporting distances less than 100m.  
Without this call CatchNearbyPokemonsTask and CatchIncensePokemonsTask dont get executed on the pokestop.
=> [Bug Fix] Teleporting less than 100m was not catching normal and incense pokemon at new pokestop. 

PoGo.NecroBot.Logic/Service/TelegramService.cs
Fix telegram /pokedex command for extramissing no
--- Pokedex needed --- 
_#0# Name: Translation for pokemon Missingno is missing_ 
#2# Name: Ivysaur 
#3# Name: Venusaur 
#5# Name: Charmeleon
=> Fix telegram /pokedex command for missing no

PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Settings.cs, PoGo.NecroBot.Logic/Tasks/UseIncubatorsTask.cs
I've updated the minEggKm for limited incubators pull request to now by default do nothing. The user can then change the setting to 5 or 10 km to only allow these eggs in the incubator.
=> minEggKm for limited incubators (updated default value)

PoGo.NecroBot.Logic/Common/ApiFailureStrategy.cs
When Tasks are cancelled there isn't an InnerException so this code throws another unhandled exception with a NPR.
=> InnerException isn't always defined

PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Settings.cs, PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
Currently, config settings for sources of sniping information are specified as follows:
"GetSniperInfoFromPokezz": false,
"GetSniperInfoFromPokeSnipers": true,
"GetSniperInfoFromPokeWatchers": false,
"SnipeWithSkiplagged": true,
This PR renames SnipeWithSkiplagged to GetSniperInfoFromSkiplagged in order to unify config setting names.
none
=> Replace SnipeWithSkiplagged by GetSniperInfoFromSkiplagged

PoGo.NecroBot.CLI/App.config, PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj, PoGo.NecroBot.ConfigUI/App.config, PoGo.NecroBot.ConfigUI/PoGo.NecroBot.ConfigUI.csproj, PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj, PoGo.NecroBot.Logic/app.config
Upgrade from .NET 4.5.2 to .NET 4.6.2. .NET 4.6.2 is supported on Windows 7 and above. This would only exclude Windows Vista, as XP doesn't even support 4.5.2.
=> Upgrade to .NET Framework 4.6.2

PoGo.NecroBot.Logic/ILogicSettings.cs, PoGo.NecroBot.Logic/Inventory.cs, PoGo.NecroBot.Logic/Settings.cs
Allow multiple movesets to be defined per pokemon.
```
"Moves": [
["QuickAttack","AirCutter"],
["Bash","AirCutter"]
]
```
*Note*: Might cause on update the loss of old Move settings. This is due to new data structures that are not transferable.
#4239
=> Allow multiple movesets to be defined.

PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
Fixes pokezz sniping when pokezz website is down.   Currently, if pokezz is not responding, then the bot will just do nothing when it starts to snipe.  It just waits indefinitely.
Now I've added a 5 second timeout, so that bot continues along if pokezz is not responding within 5 seconds.
=> Bug fix - Sniping from pokezz fixed after pokezz implementation change

PoGo.NecroBot.CLI/App.config, PoGo.NecroBot.CLI/packages.config
Fixes to get the project compiling again under .NET 4.5.2.  
1. Change App.config supported runtime to 4.5.2
2. Change packages to 4.5.2
3. Revert FeroxRev back to revision that compiled targetting 4.5.2.
=> More changes to compile under .NET 4.5.2.

PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
Fixes broken skiplagged sniping.
Skiplagged started to black list the user agent we were using.  We were seeing this response:
```
{"pokemons":[], "error": "This is an illegal request, you are being watched. Either you stop immediately or we will report this to authorities."}
```
Changing the user agent fixes this.
=> Bug fix - Fix skiplagged sniping (broken due to blacklisting of user agent)

PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs, PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs, PoGo.NecroBot.Logic/Tasks/LevelUpPokemonTask.cs, PoGo.NecroBot.Logic/Tasks/RecycleItemsTask.cs, PoGo.NecroBot.Logic/Tasks/RenamePokemonTask.cs, PoGo.NecroBot.Logic/Tasks/TransferDuplicatePokemonTask.cs, PoGo.NecroBot.Logic/Tasks/TransferWeakPokemonTask.cs
Currently TransferPokemons task's do not refresh the cached inventory before looking for pokemon to transfer.  
When EvolvePokemonTask finishes evolving it does not update the cache. 
This can cause TransferPokemon to attempt to transfer pokemon that do not exist anymore or not transfer newly evolved duplicate pokemon. 
All tasks to change pokemon and inventory should refresh cache before and after (or maybe just after?) their operations.
TransferPokemons already have Inventory.DeletePokemonFromInvById that updates the cache after a transfer but the other tasks do not have corresponding methods.
Then we dont have to RefreshCachedInventory in FarmPokemonTask (which is currently incorrectly checking whether or not to refresh, fortsearch is only the last fort not the previous 6-12).
=> [Bug Fix] TransferPokemonTask's do not RefreshCachedInventory before deciding what to transfer

PoGo.NecroBot.CLI/Config/Translations/translation.ja-JP2.json
Currently, Necrobot is There is a bug in the display of the double-byte character.
Therefore, we have Japanese the only Pokemon name and moves.
Does not cause a bug for that is described in the 1-byte character.
Please use here until the bug is avoided.
=> ADD translation.ja-JP2.json

PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
This is a follow-up fix for the pokewatchers sniping code.  Mr. Mime's data comes in from pokewatchers as "Mr_mime", so we need to change this to "MrMime" to match our enum.
This a follow-up to #5156.
=> Normalize Mr Mime data from pokewatchers.

PoGo.NecroBot.Logic/Event/PokemonCaptureEvent.cs, PoGo.NecroBot.Logic/Event/PokemonEvolveEvent.cs, PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs, PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs, PoGo.NecroBot.Logic/Tasks/EvolveSpecificPokemonTask.cs
Extended the PokemonEvolveEvent and PokemonCaptureEvent classes with a ulong field for storing the unique pokemon ID to be sent out through the websocket notifications.
Enhanced the EvolvePokemonTask, EvolveSpecificPokemonTask and the CatchPokemonTask so they fill out these new fields when the event objects are created.
https://github.com/NECROBOTIO/NecroBot/issues/4014
=> Return unique pokemon id with evolve/catch notification

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj, PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190. ..\..\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets 1820 5 PoGo.NecroBot.CLI
[405f8b9](https://ci.appveyor.com/project/NecronomiconCoding/necrobot-xyvdm/build/0.5.1409/messages)
PoGo.NecroBot.Logic
PoGo.NecroBot.CLI
[78b9c3b](https://ci.appveyor.com/project/NecronomiconCoding/necrobot-xyvdm/build/0.5.1410/messages)
PoGo.NecroBot.CLI
[8fcb33b](https://ci.appveyor.com/project/NecronomiconCoding/necrobot-xyvdm/build/0.5.1411/messages)
PoGo.NecroBot.CLI
[fde90b9](https://ci.appveyor.com/project/NecronomiconCoding/necrobot-xyvdm/build/0 …
=> Fixed Building Warning Message
