NECROBOTIO/NecroBot

PokemonGo.RocketAPI/Login/GoogleLogin.cs

So that you can just click CTRL + V and start.

Copy Device Code and Start browser

---

PokemonGo.RocketAPI.Logic/Logic.cs
PokemonGo.RocketAPI/Client.cs

Will now use if capture probablity is lower than 0.35 and pokemon has high CP OR pokemon has the min IV percent

Better logic for using berry

---

PokemonGo.RocketAPI.Console/ConsoleLogger.cs
PokemonGo.RocketAPI.Logic/Logic.cs
PokemonGo.RocketAPI/Logger.cs

Added different colour for the different events: None, Error, Warning, Info, Pokestop, Farming, Recycling, Berry, Caught, Transfer, Evolve, Debug.
Based off my personal preference and so I don't have to keep changing them all the time.

More colour options for events.

---

PokemonGo.RocketAPI.Console/ConsoleLogger.cs

Changed the berries to better match to the "capturing" related events and the item deletions to red.

color changes

---

PokemonGo.RocketAPI/Proto/AllEnum.proto

Noticed this and it was bothering me.

Fixed typo for geodude in proto

---

PokemonGo.RocketAPI.Logic/Logic.cs

peeps were complaining about too much white space

Changed tab to space for minor beauty enhancements

---

PokemonGo.RocketAPI.Logic/Inventory.cs

Move the Favorite check to the DeployedFortId check ;-)

Update Inventory.cs // Move the Favorite check to the DeployedFortId check ;-)

---

PokemonGo.RocketAPI.Logic/Logic.cs

Fixes the recycle message to properly print out the item name instead of it's ID.

Fix Recycle Message

---

PokemonGo.RocketAPI/Client.cs

Properly checking if coords IsNaN then dont fill the coords.txt

Displayhighestperfect at start fix.

---

PokemonGo.RocketAPI.Logic/Logic.cs

As discussed on discord, this recycles only when the threshold of items is between 200 and 250 items.

Recycle items at random threshold

---

PokemonGo.RocketAPI.Console/Configs/ConfigPokemonsToKeep.txt

Edited accordingly

---

PokemonGo.RocketAPI/Client.cs
PokemonGo.RocketAPI/Exceptions/AccessTokenExpiredException.cs
PokemonGo.RocketAPI/Exceptions/AccountNotVerifiedException.cs
PokemonGo.RocketAPI/Exceptions/InvalidResponseException.cs
PokemonGo.RocketAPI/Exceptions/PTCOfflineException.cs
PokemonGo.RocketAPI/Extensions/DateTimeExtensions.cs
PokemonGo.RocketAPI/Extensions/HttpClientExtensions.cs
PokemonGo.RocketAPI/Helpers/Git.cs
PokemonGo.RocketAPI/Helpers/HttpClientHelper.cs
PokemonGo.RocketAPI/Helpers/JsonHelper.cs
PokemonGo.RocketAPI/Helpers/ProtoHelper.cs
PokemonGo.RocketAPI/Helpers/RandomHelper.cs
PokemonGo.RocketAPI/Helpers/RequestBuilder.cs
PokemonGo.RocketAPI/Helpers/RetryHandler.cs
PokemonGo.RocketAPI/Helpers/S2Helper.cs
PokemonGo.RocketAPI/Helpers/Utils.cs
PokemonGo.RocketAPI/ISettings.cs
PokemonGo.RocketAPI/Logger.cs
PokemonGo.RocketAPI/Logging/ILogger.cs
PokemonGo.RocketAPI/Login/GoogleLogin.cs
PokemonGo.RocketAPI/Login/PtcLogin.cs
PokemonGo.RocketAPI/PokemonInfo.cs
PokemonGo.RocketAPI/Properties/AssemblyInfo.cs

Cleaned some code & variable naming

Some Cleanup

---

PokemonGo.RocketAPI.Logic/Logic.cs

Clean up the inconsistency of catch success vs failure messages.
Add attempt counter.

Improve CATCH logging. Add attempt counter.

---

PokemonGo.RocketAPI.Logic/Logic.cs

Shouldn't be possible to attempt a berry throw when you have no berries.

Prevent berry usage when there aren't any.

---

README.md

removed empty urls from features list

Last Update README.md

---

PokemonGo.RocketAPI.Console/Settings.cs
PokemonGo.RocketAPI.Console/UserSettings.Designer.cs
PokemonGo.RocketAPI.Console/UserSettings.settings
PokemonGo.RocketAPI.Logic/Inventory.cs
PokemonGo.RocketAPI.Logic/Logic.cs
PokemonGo.RocketAPI/GeneratedCode/Payloads.cs
PokemonGo.RocketAPI/ISettings.cs

Added Prioritize IV over CP toggleable option

---

PokemonGo.RocketAPI.Logic/Logic.cs

levels below 10 will destroy the layout

fixed Lvl-output

---

PokemonGo.RocketAPI/Client.cs

maybe walking in straight lines (from pokestop to pokestop) will be a little bit suspicious.
this adds a little bit noise to the lat and lng. (<= 4m in 50% of all cases)

add some noise to coordinates

---

PokemonGo.RocketAPI.Logic/Inventory.cs

Put KeepMinCP from Logics.cs direct into the Inventory Query

Update Inventory.cs // Change KeepMinCP Part I

---

PokemonGo.RocketAPI.Console/App.config
PokemonGo.RocketAPI.Console/Settings.cs
PokemonGo.RocketAPI.Console/UserSettings.Designer.cs
PokemonGo.RocketAPI.Console/UserSettings.settings
PokemonGo.RocketAPI/Client.cs
PokemonGo.RocketAPI/ISettings.cs

Instead of having to recreate tokens every time you move directories, move token save to GoogleAuth.ini.

Move google auth token to "GoogleAuth.ini"

---

PokemonGo.RocketAPI/ISettings.cs

Evolve all pokemon can be true and/or evolveallaboveiv
there evolveaboveivvalue comes into play ...

EvolveAllPkm Management - Evolve all above certain IV value

---

PokemonGo.RocketAPI/Client.cs
README.md

Clean up for consistency with other configs

Move Coords.txt to Configs folder as an .ini

---

PokemonGo.RocketAPI.Console/Settings.cs

Made a very small fix on PokemonsNotToCatch. Now it wont by default catch 
Zubat
Pidgey
Rattata

Small fixes for PokemonsNotToCatch

---

PokemonGo.RocketAPI.Logic/Utils/Statistics.cs

This code will make 0.75h to level up, go into 0.45h to levelup instead :)

Show next level up in actual hours and minutes

---

PokemonGo.RocketAPI.Console/ConsoleLogger.cs

Remember to change to a font that supports your language, otherwise it'll still show as ???.

Added Unicode support

---

PokemonGo.RocketAPI.Logic/Inventory.cs
PokemonGo.RocketAPI.Logic/Logic.cs

After we transferred pokemon, i just deleted that pokemon from inventory, locally.That solved the problem.

Fixed Transfer Duplicate lines,that caused by cachedInventory.

---

PokemonGo.RocketAPI.Logic/Logic.cs

The data is stale if you don't put it right about where it is needed and never gets stops

Fix issue with pokestops and gpx

---

PokemonGo.RocketAPI.Console/PokemonGo.RocketAPI.Console.csproj
PokemonGo.RocketAPI.Console/Settings.cs
PokemonGo.RocketAPI.Logic/Logic.cs
PokemonGo.RocketAPI/Logger.cs
PokemonGo.RocketAPI/Properties/AssemblyInfo.cs

-rename .txt to .ini
-create .ini files with default values if not exist
-create config and log folders at run time instead of post build
-fixed file name exception for logger

[Feature] External Item List Config

---

PokemonGo.RocketAPI.Console/ConsoleLogger.cs
PokemonGo.RocketAPI.Logic/Logic.cs
PokemonGo.RocketAPI/Logger.cs

Removed lucky egg spam.
removed 30 minute wait after using a lucky egg.
Added EGG log level.
Changed Logger to use an hourly log file instead of one every minute.

Lucky egg changes

---

PokemonGo.RocketAPI.Logic/Logic.cs

Simpple channge makes it look better

---

PoGo.NecroBot.CLI/Program.cs
PoGo.NecroBot.CLI/Settings.cs

Creates new settings file in \Configs\Settings.ini
Human readable

Add JSON Settings

---

PoGo.NecroBot.CLI/Settings.cs
PoGo.NecroBot.Logic/ILogicSettings.cs
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/State/FarmState.cs
PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs
PoGo.NecroBot.Logic/Tasks/RenamePokemonTask.cs

Should help a few of the requests people have made. Makes it easier than trying to find even in the display once that gets redone.

[Feature] Rename Pokemon above KeepIvPercent with Iv value in name

---

PoGo.NecroBot.Logic/State/InfoState.cs

In case someone doesn't want the input at all

Disabled display of pkm in case it is set to 0

---

PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/State/VersionCheckState.cs

can download, extract, replace, and cleanup old files
needs final changes to IsLatest to function 100%

fixup part 1 of auto update

---

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.CLI/packages.config

fresh clones were getting errors about pogoprotos not being found
this fixes it

fix pogo proto not being found

---

PoGo.NecroBot.Logic/Inventory.cs
PoGo.NecroBot.Logic/Navigation.cs
PoGo.NecroBot.Logic/State/FarmState.cs
PoGo.NecroBot.Logic/State/IState.cs
PoGo.NecroBot.Logic/State/InfoState.cs
PoGo.NecroBot.Logic/State/LoginState.cs
PoGo.NecroBot.Logic/State/PositionCheckState.cs
PoGo.NecroBot.Logic/State/StateMachine.cs
PoGo.NecroBot.Logic/State/VersionCheckState.cs
PoGo.NecroBot.Logic/Tasks/CatchIncensePokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchLurePokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs
PoGo.NecroBot.Logic/Tasks/DisplayPokemonStatsTask.cs
PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/FarmPokestopsGPXTask.cs
PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs
PoGo.NecroBot.Logic/Tasks/LogBestPokemonTask.cs
PoGo.NecroBot.Logic/Tasks/RecycleItemsTask.cs
PoGo.NecroBot.Logic/Tasks/RenamePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/TransferDuplicatePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs

I've basically done one thing in many places: Replace .Wait() and .Result with proper awaiting.
The only other thing I did was removing the StateMachine.RequestDelay() method, and used Task.Delay() instead.

Use async/await in tasks and states [fixed]

---

PoGo.NecroBot.Logic/Inventory.cs

it wasnt fixed previous pr sorry for that  :(

CandyCount while transferPokemon Now Fixed !

---

PoGo.NecroBot.CLI/ConsoleEventListener.cs

The additions of the translation changed the precision of distance print to be unnecessarily long.

Added 2 decimal precision for distance

---

NecroBot/PoGo.NecroBot.CLI/bin/Debug/config/translations/translation.nl

Possible contribution untill I finish my C# tutorials

Dutch translation

---

translation.it.json

Of all the project I've found around this is the one I like most, for various reasons, so I'll start contributing as I can.
At the moment that would be this :D
Also first time using github so sorry in advance for any mistake

Italian Translation

---

PoGo.NecroBot.CLI/Translations/translation.zh_CN.json

add Simplified Chinese Translation

Simplified Chinese Translation

---

Translations/translation.es.json

Didn't know where to place it, so created the folder Translations at root and added the spanish translation file there.
(it's spanish from spain)

Spanish Translation

---

translation.pl

Will try to keep this file up to date with new versions.

Polish Translation

---

PoGo.NecroBot.CLI/Settings.cs

Like it stays in the Wiki under PrioritizeIVOverCP... should be false and some other adjustments

[Suggestions] Update settings.cs

---

Translations/translation.de.json

German Translation

---

PoGo.NecroBot.CLI/Config/Translations/translation.pt-br.json

Brazilian Portuguese Translation

---

PoGo.NecroBot.CLI/Config/Translations/translation.de.json

added 2 new Keys
changed one sentence to sound more natural

update german translation

---

PoGo.NecroBot.CLI/Program.cs
PoGo.NecroBot.Logic/Logging/Logger.cs

Barely larger than the Eevee typo

Remove path separator char prepended to profile, as this breaks Path.Combine

---

PoGo.NecroBot.CLI/Program.cs
PoGo.NecroBot.Logic/Settings.cs

Just checks if the config exists
yes -> continues normally 
no -> asks if you want to continue with the default config
#793

Asks if you want to continue on first start

---

PoGo.NecroBot.CLI/Config/Translations/translation.de.json

a complete translation
#1070 forgot some sentences

update for german translation... complete

---

PoGo.NecroBot.Logic/Settings.cs

Optimal config for most people
(I've tested quite bot before suggesting this. and I have discussed with my friends who use. Feel free to add changes and/or discuss it)

Optimal default config - Update Settings.cs

---

PoGo.NecroBot.Logic/Inventory.cs

Remove unnecessary if nesting

---

PoGo.NecroBot.CLI/Config/Translations/translation.de.json

DE Language update. Added missing Lines.

Update for Language DE / german added missing lines

---

PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/Tasks/FarmPokestopsGPXTask.cs
PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs
PoGo.NecroBot.Logic/Utils/EggWalker.cs

Which also resolves [this](https://github.com/NecronomiconCoding/NecroBot/issues/976#issuecomment-235752966) comment about incubation checks with GPX

Distance-based incubation checks

---

PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs

Fix error when catch incense pokemon, fortdata is null.

Fix Incense Pokemon Catch Task

---

PoGo.NecroBot.Logic/Inventory.cs

Fixed issue https://github.com/NecronomiconCoding/NecroBot/issues/995

Fixed duplicate skip of KeepMinDuplicatePokemon

---

PoGo.NecroBot.Logic/Settings.cs

Hotfix to save new Settings feature not only on first start

---

PoGo.NecroBot.Logic/Settings.cs

More optimal settings to avoid full PokeInventory

---

PoGo.NecroBot.Logic/State/Session.cs

https://github.com/FeroxRev/Pokemon-Go-Rocket-API/pull/55

Critical auth fix for PTC users

---

PoGo.NecroBot.Logic/Settings.cs
PoGo.NecroBot.Logic/Utils/DelayingUtils.cs

https://github.com/NecronomiconCoding/NecroBot/commit/af39dae857fe3c6312e2f29014a60ab86e318131
not even compile tested?

Fix random delays and DelayBetweenPlayerActions compile errors

---

PoGo.NecroBot.CLI/Config/Translations/translation.ru_RU.json

Updated russian translation

---

PoGo.NecroBot.Logic/Utils/DelayingUtils.cs

Replaced asynchronical delay with synchronical one.

fix: DelayUtils not delaying (changed to sync mode)

---

PoGo.NecroBot.CLI/Config/Translations/translation.ru_RU.json
PoGo.NecroBot.Logic/Common/Translations.cs

FIxed serializer to be able to deserialize translation files correctly

Fixed translations not loading

---

PoGo.NecroBot.CLI/Config/Translations/translation.ru_RU.json
PoGo.NecroBot.Logic/Common/Translations.cs

Workaround for json unable to fill missing translation parts from default values

Fixed translations to use default values + updated russian translation

---

PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

Due to null value pokemon object

Fixed snipe logic crash

---

PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

Culture fix/hack in SnipePokemonTask.cs

---

PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

Revert "Culture fix/hack in SnipePokemonTask.cs"

---

PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

Now you wont have to change windows settings to get it working.

Fix sniping for countries using a comma as separator

---

PoGo.NecroBot.Logic/ILogicSettings.cs
PoGo.NecroBot.Logic/Settings.cs
PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

Disabled Sniping by default.
Setting to stop sniping if under min pokeball amount (20 default)

Sniping Updates

---

PoGo.NecroBot.Logic/Navigation.cs
PoGo.NecroBot.Logic/State/FarmState.cs
PoGo.NecroBot.Logic/State/IState.cs
PoGo.NecroBot.Logic/State/InfoState.cs
PoGo.NecroBot.Logic/State/LoginState.cs
PoGo.NecroBot.Logic/State/PositionCheckState.cs
PoGo.NecroBot.Logic/State/StateMachine.cs
PoGo.NecroBot.Logic/State/VersionCheckState.cs
PoGo.NecroBot.Logic/Tasks/CatchIncensePokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchLurePokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/Farm.cs
PoGo.NecroBot.Logic/Tasks/FarmPokestopsGPXTask.cs
PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs
PoGo.NecroBot.Logic/Tasks/RecycleItemsTask.cs
PoGo.NecroBot.Logic/Tasks/RenamePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/TransferDuplicatePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/UseIncubatorsTask.cs
PoGo.NecroBot.Logic/Tasks/UseNearbyPokestopsTask.cs
PoGo.NecroBot.Logic/Utils/EggWalker.cs

Added cancellationtoken to support cancelling the bot. 
With this it could be stopped and started at any given time.
Followed the good practices and not cancelling operations after the point of no cancellation. 
For example when the lucky egg is used, the operation won't be cancelled before all pokemons are evolved otherwise the lucky egg would be wasted.

Added cancellationtoken

---

PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

SniperPokemonTask.cs - Useless line.

---

PoGo.NecroBot.Logic/Common/Translations.cs

This bugged me from day 1. I formatted the numbers in the program title for commas.

Title number comma formatting

---

PoGo.NecroBot.CLI/Config/Translations/translation.sv.json
PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj

Added Swedish translation (sv)

Added Swedish translation

---

PoGo.NecroBot.CLI/Config/Translations/translation.ru_RU.json

 Updated russian translation file

---

PoGo.NecroBot.CLI/Config/Translations/translation.id.json
PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj

Adding, translating and fixing new keys and values from translation.en.json to translation.id.json

Adding, translating and fixing new keys and values from translation.en.json to translation.id.json

---

PoGo.NecroBot.CLI/Config/Translations/translation.fr.json

Hi.
Updated the french language, added missing strings and fixed others to make reading easier.
Added
"eventFortFailed"
"commonWordUnknown"
"invFullPokestopLooting"
"webSocketFailStart"
"googleTwoFactorAuth"
"googleTwoFactorAuthExplanation"
"googleError"
"missingCredentialsGoogle"
"missingCredentialsPtc"
"snipeScan"
"noPokemonToSnipe"

Updated French language

---

PoGo.NecroBot.Logic/Settings.cs

Dont know if they do it. But better safe than sorry!

[add] Never spawn at the same position. Niantic might detect that!

---

PoGo.NecroBot.CLI/Config/Translations/translation.da.json
PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj

Translated the German translation file into a Danish translation file,
corrected the directory and added it to .csproj

Added Danish translation file [Fixed with .csproj]

---

PoGo.NecroBot.Logic/State/PositionCheckState.cs

so we can show the map before all the cleaning in inventory that takes some time

Event: send current position on start

---

PoGo.NecroBot.Logic/ILogicSettings.cs
PoGo.NecroBot.Logic/Settings.cs
PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs

A futureproofing list filter for if/when we do get master balls that if empty will still continue like it currently does as last priority ball, otherwise if there's something in the list it should only throw a Masterball on those.

Never waste Masterballs on non-legendary.

---

PoGo.NecroBot.Logic/ILogicSettings.cs
PoGo.NecroBot.Logic/Settings.cs
PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs

Updated.
Customizable pokeball based on CP.
Thanks to @mich3lam for fixing code.

Custom pokeballs

---

PoGo.NecroBot.CLI/Config/Translations/translation.id.json

This commit is done to further translate EN words that haven't been translated into ID as well as fixing Bahasa wordings to match with the English meaning.

Updating Bahasa translation

---

PoGo.NecroBot.Logic/Settings.cs

• Added Farfetchd
• Added Kangaskhan
• Added MrMime
• Added Scyther
• Added Electabuzz
• Added Magmar
• Added Tauros
• Added Gyarados
• Added Lapras
• Added Eevee
• Added Vaporeon
• Added Jolteon
• Added Flareon
• Added Porygon
• Added Snorlax
• Added Dragonite

Optimized PokemonsTransferFilter for sniping

---

PoGo.NecroBot.Logic/Settings.cs

Explicit double cast, not sure if nessecary?

Offset parameter explicitcast

---

PoGo.NecroBot.Logic/Tasks/LevelUpPokemonTask.cs

So we don't pick the same number every time

Fix RNG in UpgradePokemon

---

PoGo.NecroBot.Logic/Tasks/DisplayPokemonStatsTask.cs

Wasnt upgrading when absolute value was specified, e.g. wanting only
100% IV uprades.

Upgrade fix

---

README.md

Not at all code related - feel free to close if this is a stupid pull request, which it probably is.

Updated README with two lines

---

PoGo.NecroBot.CLI/Config/Translations/translation.ca.json

Added NecroBot translation to Catalan language.

Add translation.ca.json

---

PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs

Removed a code which makes bot to use greatball on ANY pokemon above 300 CP

Bot was catching all pokemons above 300 with greatball

---

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.CLI/WebSocketHandler/BasicGetCommands/Events/PokemonListResponce.cs
PoGo.NecroBot.CLI/WebSocketHandler/BasicGetCommands/GetPokemonListHandler.cs
PoGo.NecroBot.CLI/WebSocketHandler/BasicGetCommands/Helpers/PokemonListWeb.cs
PoGo.NecroBot.CLI/WebSocketHandler/BasicGetCommands/Tasks/GetPokemonListTask.cs
PoGo.NecroBot.CLI/WebSocketHandler/EncodingHelper.cs
PoGo.NecroBot.CLI/WebSocketHandler/IWebSocketRequestHandler.cs
PoGo.NecroBot.CLI/WebSocketHandler/IWebSocketResponce.cs
PoGo.NecroBot.CLI/WebSocketHandler/WebSocketEventManager.cs
PoGo.NecroBot.CLI/WebSocketInterface.cs

Updates / decoupling to websockets interface to make it easier for people to add their own handlers.
- 1. Plugin style auto registering of new handlers.
- 2. Keeps broadcasting all events to all sessions.
- 3. Setup with view of sending commands via WebSockets. 
- 4. Doesn't send type data in responses (not needed in JS)
- 5. Working with web based GUI i'm working on (release tomorrow maybe..)

Updates to websockets to handle command based communcation

---

PoGo.NecroBot.CLI/Config/Translations/translation.it.json

Fixed:
LogEntryPKMN > LogEntryPkmn
DisplayHighestMOVEXHeader > DisplayHighestMoveXHeader

Updated translation.it.json

---

PoGo.NecroBot.CLI/Config/Translations/translation.id.json

Adding several translation items

Updating Bahasa Indonesia

---

PoGo.NecroBot.Logic/ILogicSettings.cs
PoGo.NecroBot.Logic/Settings.cs
PoGo.NecroBot.Logic/Tasks/LevelUpPokemonTask.cs

Will fix an exception people getting 
and can loop through upgrades (will stop if detects not enough resources)

Fixes Exception for max level and add how many times you want to loop through upgrades

---

PoGo.NecroBot.Logic/Inventory.cs
PoGo.NecroBot.Logic/Tasks/RecycleItemsTask.cs

LogLevel.Recycling Fix

---

PoGo.NecroBot.Logic/ILogicSettings.cs
PoGo.NecroBot.Logic/Settings.cs
PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

Implemented boundaries for sniping, configurable in settings with default of 0.003 which is half a mile, maximum 10 miles.

Implemented boundaries for sniping

---

PoGo.NecroBot.Logic/ILogicSettings.cs
PoGo.NecroBot.Logic/Inventory.cs
PoGo.NecroBot.Logic/PoGo.NecroBot.Logic.csproj
PoGo.NecroBot.Logic/Settings.cs
PoGo.NecroBot.Logic/State/FarmState.cs
PoGo.NecroBot.Logic/Tasks/Farm.cs
PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs
PoGo.NecroBot.Logic/Tasks/UseIncenseConstantlyTask.cs
PoGo.NecroBot.Logic/Tasks/UseLuckyEggConstantlyTask.cs

Option to use luckyegg and incense constantly wont waste them either so will renew every 30 minutes can be disabled if wanted

Use Lucky Egg and incense constantly

---

PoGo.NecroBot.Logic/State/FarmState.cs
PoGo.NecroBot.Logic/Tasks/UseIncenseConstantlyTask.cs
PoGo.NecroBot.Logic/Tasks/UseLuckyEggConstantlyTask.cs

It will now first check if the settings are enabled, then check if there is any of the item in your inventory, and then try to use it, and properly display the message regarding its usage.

Fixed lucky egg and incense functionalities

---

PoGo.NecroBot.CLI/Program.cs
PoGo.NecroBot.Logic/ILogicSettings.cs
PoGo.NecroBot.Logic/PoGoUtils/PokemonInfo.cs
PoGo.NecroBot.Logic/Settings.cs
PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

Some minor fixes and improvements

Some minor fixes and improvements

---

.gitmodules
PoGo.NecroBot.CLI/Program.cs
PoGo.NecroBot.Logic/Common/ApiFailureStrategy.cs

Reverts NecronomiconCoding/NecroBot#1524

Revert "Switch to FeroxRev Repo for API"

---

PoGo.NecroBot.CLI/Config/Translations/translation.fr.json
PoGo.NecroBot.Logic/Common/Translations.cs

- Fixed #1624 who was change PotentialEvolveCount to pkmPotentialEvolveCount  @SpartaGH
- Fixed missing {0} "Value": "[Evolution] Total envisageable : {0}" - translation.fr.json
- Added MaxItemsCombinedOverMaxItemStorage
- Added RecyclingQuietly
- Fixed missing {0} PkmPotentialEvolveCount - Translation.cs
- Fixed for #1696 error compiling

Fixed French, Issue #1624

---

PoGo.NecroBot.CLI/Config/Translations/translation.id.json

This fixes some untranslated strings and using more indonesian terms of things.

Bahasa Indonesia: Fix and update translations.

---

PoGo.NecroBot.CLI/Config/Translations/translation.id.json

Updated accordingly to the new english translation and translated the
remaining untranslated strings.

Bahasa Indonesia: Moar fixes and untranslated strings.

---

PoGo.NecroBot.CLI/Config/Translations/translation.fr.json

Fixed :
eventFortTargeted
accountNotVerified
downloadingUpdate
RealisticTravelDetected _- revert, not translated_
PkmPotentialEvolveCount
notEnoughPokeballsToSnipe
snipeScanEx
currentPokeballInv
Added :
SnipeServerOffline
WaitingForMorePokemonToEvolve
UseLuckyEggsMinPokemonAmountTooHigh
CatchMorePokemonToUseLuckyEgg

Update French language

---

PoGo.NecroBot.CLI/Config/Translations/translation.fr.json

Fixed SnipeScanEx
Compilation error

[FR] Fixed Compilation error

---

PoGo.NecroBot.Logic/Settings.cs
PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/RecycleItemsTask.cs

Fixing issue 1966 with this request.

issue #1966

---

PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs

too early in the morning. this should fix the incorrect log. logic was fine

issue #1966 fix incorrect log

---

PoGo.NecroBot.CLI/Config/Translations/translation.da.json
PoGo.NecroBot.CLI/Config/Translations/translation.de.json
PoGo.NecroBot.CLI/Config/Translations/translation.es.json
PoGo.NecroBot.CLI/Config/Translations/translation.et.json
PoGo.NecroBot.CLI/Config/Translations/translation.fr.json
PoGo.NecroBot.CLI/Config/Translations/translation.gr.json
PoGo.NecroBot.CLI/Config/Translations/translation.hu.json
PoGo.NecroBot.CLI/Config/Translations/translation.id.json
PoGo.NecroBot.CLI/Config/Translations/translation.it.json
PoGo.NecroBot.CLI/Config/Translations/translation.lt.json
PoGo.NecroBot.CLI/Config/Translations/translation.nl.json
PoGo.NecroBot.CLI/Config/Translations/translation.no.json
PoGo.NecroBot.CLI/Config/Translations/translation.pl.json
PoGo.NecroBot.CLI/Config/Translations/translation.pt-br.json
PoGo.NecroBot.CLI/Config/Translations/translation.pt-pt.json
PoGo.NecroBot.CLI/Config/Translations/translation.ru_RU.json
PoGo.NecroBot.CLI/Config/Translations/translation.sv.json
PoGo.NecroBot.CLI/Config/Translations/translation.th.json
PoGo.NecroBot.CLI/Config/Translations/translation.tr.json
PoGo.NecroBot.CLI/Config/Translations/translation.uk_UA.json
PoGo.NecroBot.CLI/Config/Translations/translation.zh_CN.json
PoGo.NecroBot.CLI/Config/Translations/translation.zh_tw.json
PoGo.NecroBot.CLI/ConsoleEventListener.cs
PoGo.NecroBot.Logic/Common/Translations.cs
PoGo.NecroBot.Logic/Tasks/CatchIncensePokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/DisplayPokemonStatsTask.cs
PoGo.NecroBot.Logic/Tasks/FavoritePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/LevelUpPokemonTask.cs
PoGo.NecroBot.Logic/Tasks/RenamePokemonTask.cs

Added german pokemon translation
Added Empty-Array of translations for other languages (so default is english)

Translations for Pokemon possible

---

PoGo.NecroBot.CLI/ConsoleEventListener.cs
PoGo.NecroBot.Logic/Common/Translations.cs

Added lat and long info to pokestop output so its easier to follow the bot and know where it is

Add lat and long to EventFortUsed event

---

PoGo.NecroBot.CLI/Config/Translations/translation.fr.json
PoGo.NecroBot.Logic/Inventory.cs
PoGo.NecroBot.Logic/Settings.cs

Typos:
itemsToRecylce -> itemsToRecycle
TotalAmountOfPokebalsToKeep -->TotalAmountOfPokeballsToKeep
French pre-updates:
eventFortUsed #2037 
eventPokemonCapture #2035

Fixed typos + French

---

PoGo.NecroBot.CLI/Config/Translations/translation.de.json

Fixed RequireInputText
Program -> Programm

Fixed Typo for De  #2155

---

PoGo.NecroBot.Logic/Logging/Logger.cs

Added clear to LogbufferList. Otherwise every minute the log will be duplicated including new lines.

Logbuffer clear

---

PoGo.NecroBot.CLI/Config/Translations/translation.da.json

Updated with Snipe info, and fixed some misspellings.

Updated Danish translation file

---

PoGo.NecroBot.CLI/ConsoleEventListener.cs

Not sure about the failed case but the success was missing translation.

Adds missing translation when evolving

---

PoGo.NecroBot.CLI/ConsoleEventListener.cs
PoGo.NecroBot.Logic/ILogicSettings.cs
PoGo.NecroBot.Logic/Settings.cs

fixed issue #2303 and changed UseGreatBallAboveIv and UseUltraBallAboveIv to percentages as requested in #2165

fixed/changed #2303 & #2165

---

PoGo.NecroBot.Logic/Inventory.cs
PoGo.NecroBot.Logic/Settings.cs
PoGo.NecroBot.Logic/Tasks/TransferDuplicatePokemonTask.cs

transfer pokemon task refactor, faster and better code, main feature counting pokemon that we can keep for evolve according to new candy count from some of pokemon that we will only transfer at this moment

Inventory transfer function refactoring, improve and fixes of some wrong behaviors

---

translation.de.json

Changed line 574 from NidoranF ->Nidoran ♀ and line 586NidoranM ->Nidoran ♂

[UPDATE] translation.de.json

---

PoGo.NecroBot.CLI/Config/Translations/translation.it.json

fixed some italian grammar, and removed 1 duplicated key

fixed grammar in translation.it.json

---

PoGo.NecroBot.CLI/Config/Translations/translation.es.json

I have made minor tweaks to the Spanish translations.

Minor update to translation.es.json

---

PoGo.NecroBot.CLI/Config/Translations/translation.zh_TW.json

Update and rename translation.zh_tw.json to translation.zh_TW.json

---

PoGo.NecroBot.CLI/Config/Translations/translation.pl.json

Correcting common errors in Polish Translation.

Final update to Polish Translation.

---

README.md

I updated the README in accordance to the current API situation with PokeStops.
Please feel free to reword/rephrase/add if there is anything I missed.

Updated for Current API situation

---

PoGo.NecroBot.CLI/Config/Translations/translation.de.json
PoGo.NecroBot.CLI/Config/Translations/translation.es.json
PoGo.NecroBot.CLI/Config/Translations/translation.id.json
PoGo.NecroBot.CLI/Config/Translations/translation.pt-br.json
PoGo.NecroBot.CLI/Config/Translations/translation.zh_CN.json
PoGo.NecroBot.Logic/Common/Translations.cs

Some spaces missing, pokestop time in german translation added

Text fixes

---

PoGo.NecroBot.CLI/Config/Translations/translation.de.json

Updated German Translation File

---

PoGo.NecroBot.CLI/SETUP.md

Not in the todo list but should be helpful for new users.

Add Setup.md

---

PoGo.NecroBot.CLI/Config/Translations/translation.nl.json

Update Translation NL

---

PoGo.NecroBot.CLI/Config/Translations/translation.de.json

added trnaslation for waitingForMorePokemonToEvolve

updated translation.de.json

---

PoGo.NecroBot.CLI/Program.cs

Small fix for the websocket server

Fixed websocket

---

PoGo.NecroBot.CLI/Config/Translations/translation.ro.json

I've updated Romanian translation for the latest version :)

Romanian translation updated

---

PoGo.NecroBot.CLI/Config/Translations/translation.fr.json

Hello,
I've rebased the French translation on the english to correct the rebase language error and to display Pokemon List at launch.
Thanks for your work,
Nicolas

Rebase French translation on translation.en.json

---

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj

Let's bundle all languages available in Github.
For example Romanian never landed in any release/update package.

Updated lang list + some ordering

---

PoGo.NecroBot.CLI/Config/Translations/translation.ro.json

Romanian should be now updated to v0.7.3 :)

Changes and updates for translation.ro.json

---

PoGo.NecroBot.CLI/Config/Translations/translation.de.json
PoGo.NecroBot.CLI/ConsoleEventListener.cs

substituted hard coded "unknown" with translatet string
'CommonWordUnknown'

added GetTranslation for sniping "unknown" IV pokemon

---

PoGo.NecroBot.CLI/Config/Translations/translation.es.json

Update translation es

---

PoGo.NecroBot.CLI/Config/Translations/translation.id.json

Change some translations with normal language we use on Indonesia.

Change some translations.

---

PoGo.NecroBot.CLI/Config/Translations/translation.vi.json

More Vietnamese. Easier to understand.

Make New translation.vi.json

---

PoGo.NecroBot.CLI/Config/Translations/translation.fr.json

- Corrected some sentences
- Added all moves

Updated FR translation

---

PoGo.NecroBot.CLI/Config/Translations/translation.de.json

Here is a small correction for translation.de.json

Bot/Language: Correct another German word

---

PoGo.NecroBot.CLI/Config/Translations/translation.zh_CN.json

Add some "\t" at end of line,fix the Full-width character always display half
I know this can't Radical.
But now can see all words in CLI Instead of half

Fix Full-width character not displayed correctly and update zh_CN.json

---

PoGo.NecroBot.CLI/Config/Translations/translation.it.json

I have corrected and i have added some translation for my language

Corrected Italian translation

---

PoGo.NecroBot.CLI/Config/Translations/translation.id.json

English:
Revert translations that doesn't make sense.
Fix typos.
New untranslated strings.
I'm now using the original name for items (Incense, Lucky Egg, Lure and
Razz Berry) to avoid confusion, and wait if there's any official
translation from the offical app.
---
Bahasa Indonesia:
Mengembalikan terjemahan yang tidak masuk akal.
Memperbaiki kesalahan penulisan.
Kalimat-kalimat baru yang belum diterjemahkan.
Sekarang saya pakai nama barang yang asli, supaya tidak membingungkan
(Incense, Lucky Egg, Lure, Razz Berry), sembari menunggu terjemahan
resmi dari aplikasi resmi kalau ada.
Terima kasih juga kepada @bulubebek untuk saran penggunaan katanya, serta @wakrad atas temuan kata yang belum sesuai.

Bahasa Indonesia: update and fix translations.

---

PoGo.NecroBot.Logic/Inventory.cs
PoGo.NecroBot.Logic/State/FarmState.cs
PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs
PoGo.NecroBot.Logic/Tasks/Farm.cs
PoGo.NecroBot.Logic/Tasks/FarmPokestopsGPXTask.cs
PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs
PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

Now evolving using lucky eggs and keeping Pokemon that can evolve
both work.

[BUG FIX] Fixed evolution mistakes/bugs.

---

PoGo.NecroBot.Logic/Tasks/LevelUpPokemonTask.cs

Fixed LevelUp for 100% IV

---

PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs

Forgot to remove all the debug code

---

PoGo.NecroBot.Logic/Tasks/LevelUpPokemonTask.cs

Update to reflect that the max Pokemon Level is the Trainer Level +1

Updated LevelUpPokemonTask

---

PoGo.NecroBot.CLI/Config/Translations/translation.ca.json

Updating the catalan translation to the 0.7.7 version of Necrobot.

Catalan translation update

---

PoGo.NecroBot.Logic/Tasks/EvolvePokemonTask.cs

It would evolve without using the lucky egg if KeepPokemonsThatCanEvolve was true

[Fix] Evolve bug

---

PoGo.NecroBot.CLI/Config/Translations/translation.id.json

New untranslated strings for Telegram support.

Bahasa Indonesia: Update translations.

---

PoGo.NecroBot.Logic/Common/ApiFailureStrategy.cs

Couldn't reproduce the NullRefrenceException crash.
so now it won't crash & it will output important data.
ISSUES: #3447, #3471.

NullReferenceException quick fix

---

PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

Solves #3326, issue where a sniping servers are disabled, but still attempts to pull snipe info.

Fixes #3326 Sniping with server disabled will still attepmpt to snipe.

---

PoGo.NecroBot.CLI/Config/Translations/translation.id.json

New untranslated string (from #3436)

Bahasa Indonesia: Update translation.

---

PoGo.NecroBot.Logic/Common/Translations.cs

berrys to berries and pokemon catched to pokemon caught

Changed tense on word in telegram output

---

PoGo.NecroBot.CLI/Config/Translations/translation.id.json

Readjusting some words to make it more sensible.

Fixing some of the translation.id.json

---

PoGo.NecroBot.Logic/Settings.cs

Set "DisableHumanWalking" to False
speed up can change "WalkingSpeedInKilometerPerHour" allright?
the v0.8.0 default is teleport not walking

 fix v0.8.0 speed tooooo fast cause got a lot of softbans

---

PoGo.NecroBot.CLI/Program.cs

Fixed Typo

---

PoGo.NecroBot.Logic/Settings.cs

Many people are complaining about the "Recycling Quietly..." message, and "no recycling".

Set some recycling settings to true by default.

---

PoGo.NecroBot.Logic/ILogicSettings.cs
PoGo.NecroBot.Logic/Settings.cs
PoGo.NecroBot.Logic/Tasks/LevelUpPokemonTask.cs

able to have a lost to select specific pokemon to levelup 
or choose not to use the list

Use Upgrade List and have option to use it etc

---

PoGo.NecroBot.CLI/ConsoleEventListener.cs
PoGo.NecroBot.Logic/ILogicSettings.cs
PoGo.NecroBot.Logic/Settings.cs
PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs

Added a new setting (FastSoftBanBypass), if set to true bot doesn't have any delays when bypassing the ban.
By default it's on false.

Faster softban bypass setting

---

PoGo.NecroBot.CLI/Config/Translations/translation.pt-br.json

Just As Simple, i noticed that pt-PT and pt-BR traslitions are the same, so i made an pt-BR translation for the Brazilian Portuguese Speakers

pt-Br Update

---

PoGo.NecroBot.CLI/Config/Translations/translation.sv.json

Fix for various spelling mistakes in Swedish translation

fix spelling mistakes in sv translation

---

PoGo.NecroBot.CLI/Config/Translations/translation.id.json

Pembaharuan Bahasa indonesia dari versi 8.1

Update Bahasa Indonesia

---

PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

Bug fix - Don't keep sniping pokemon that are missing.

---

PoGo.NecroBot.CLI/Config/Translations/translation.hu.json

- New telegram values translated
- googleOffline value translated
- Fixed ultra pokeball value
- Fixed farmPokestopsNoUsableFound value
- Fixed eventPokemonCaptureSuccess and eventPokemonCaptureFailed value
- Fixed couldntCopyToClipboard2 value
- Fixed currentPokeballInv, CurrentPotionInv, CurrentReviveInv, CurrentMiscItemInv value
- Fixed missingCredentialsGoogle value

Updated HU translation

---

PoGo.NecroBot.Logic/Settings.cs
PoGo.NecroBot.Logic/State/Session.cs
PoGo.NecroBot.Logic/State/StateMachine.cs

we dont have to restart, when we changed some options, now automatic
#IMPORTANT (you make sure access to config.json, otherwise you may get errors)

[now automatic] instantly update config.json file changes

---

PoGo.NecroBot.CLI/Config/Translations/translation.ro.json

All strings updated for the upcoming version (maybe v0.8.2) :)

Updated RO translation

---

PoGo.NecroBot.Logic/Tasks/LevelUpPokemonTask.cs

fixed issue where it would ignore rest of config if fave option was true

Fixed Favorite issue

---

PoGo.NecroBot.CLI/Config/Translations/translation.pt-pt.json

Added translation to Telegram
Some minor gramatical fixes (old translation might confuse with pt-BR)

Update translation pt-PT

---

PoGo.NecroBot.CLI/Config/Translations/translation.zh_CN.json

Fix Simplified Chinesetranslation

Fixed Simplified Chinese part of the name for the Nintendo official translation

---

PoGo.NecroBot.Logic/Settings.cs

Change Keepminpokemon to 1 avoid losing pokemon

---

PoGo.NecroBot.CLI/Config/Translations/translation.zh_CN_pp.json

As there are a lot of players in China (Believe me! Over half of Chinese Pokemon players at least), who used to call the pokemons and their skills with folk names, I added some popular translations of those stuff. For veterans played Pokemon since 10 years ago! Hope u guys would enjoy it! :-)

Add translation.zh_CN_pp for Old-School Veterans

---

PoGo.NecroBot.CLI/Config/Translations/translation.ro.json

It was my mistake, I've added missing text for /pokedex.

Updated RO lang

---

PoGo.NecroBot.Logic/Tasks/CatchIncensePokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchLurePokemonsTask.cs
PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs

When inventory full upon catching, trigger transfer of weak and duplicate pokemon (was: duplicates only)

When inventory full, trigger full cleanup

---

PoGo.NecroBot.Logic/Tasks/CatchNearbyPokemonsTask.cs

updated German translation for Telegram.

updated German translation for Telegram.

---

PoGo.NecroBot.Logic/Tasks/LevelUpPokemonTask.cs

Fixes break bug for high cp pokemon

---

PoGo.NecroBot.Logic/Tasks/CatchPokemonTask.cs

makes it transfer them after catch success

Fixes transfer pokemon whilst catching

---

PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

As discussed in https://github.com/NECROBOTIO/NecroBot/issues/4741.
Thanks @shcheuk  for the great find.
P.S. Thinking about it I am not 100% sure this visited check should be removed.

Fix skipplagged snipping and remove duplicate visited check.

---

PoGo.NecroBot.CLI/PoGo.NecroBot.CLI.csproj
PoGo.NecroBot.ConfigUI/App.config
PoGo.NecroBot.ConfigUI/PoGo.NecroBot.ConfigUI.csproj
PoGo.NecroBot.ConfigUI/Properties/Resources.Designer.cs
PoGo.NecroBot.ConfigUI/Properties/Settings.Designer.cs
PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

Wrapping up the revert of frameworks.

CLI and ConfigUI to 4.5.2

---

PoGo.NecroBot.CLI/Program.cs
PoGo.NecroBot.Logic/Common/Translations.cs
PoGo.NecroBot.Logic/Settings.cs

see #4143 .
fix no "translator" Problem.

Adding proxy check Translation (Again)

---

PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

Our new firewall isn't working with your HttpClient, it's detecting you as a bot trying to connect. Add this user agent and you'll be fine.

Update SnipePokemonTask.cs - Fixes PokeWatchers API

---

PoGo.NecroBot.CLI/Config/Translations/translation.zh_TW.json

Update translation.zh_TW.json (Proxy check)

---

PoGo.NecroBot.CLI/Config/Translations/translation.th.json

We receive lots of pull requests, please help us be able to review them by following the below guidelines:
1. If you are adding configuration settings, please be sure to document their usage in your description so they can be added to the wiki.
2. Make sure your code is clean and well-formed. Use comments if necessary to explain why you did something.
3. Make sure your changes are only for a specific purpose. Do not mix several changes into one pull request.
4. If the code is based off another individuals work, be sure to credit them appropriately.

Update translation.th.json Bata

---

PoGo.NecroBot.CLI/Config/Translations/translation.es.json

Update translation.es.json for telegram

Update translation.es.json for telegram

---

PoGo.NecroBot.CLI/Config/Translations/translation.id.json

Bahasa Indonesia: Telegram login translations.

---

PoGo.NecroBot.CLI/Config/Translations/translation.jp.json

create a new Japanese localization file
Ver.0.8.5
Specialthanks 2ch 25/81

translation.jp.json

---

PoGo.NecroBot.ConfigUI/MainWindow.xaml
PoGo.NecroBot.ConfigUI/MainWindow.xaml.cs
PoGo.NecroBot.ConfigUI/Models/ObservableSettings.cs

This commit finishes up the backing object for the UI and all logic to move data between GlobalSettings and ObservableSettings, fixes some of the confusion between Default and Current lat/lon, and adds the Current Lat/Lon fields to the UI. Still not quite there yet, but getting very close.

Config UI almost ready for use

---

PoGo.NecroBot.CLI/Config/Translations/translation.ro.json

Translated all new strings added.

Romanian updated

---

PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

Fixes Pokewatchers sniping not being reliable due to consistently getting error response from API:
```
You can only request the API every 5 seconds.
```
1. Now it correctly retries up to 5 times, sleeping 1 second in between.  Note that pokewatchers sniping can now wait up to 5 seconds while it is checking the API.  After retrying 5 times, it gives up and moves on.
2. Also cleaned up the code to not modify the JSON response from pokewatchers.  The response modification was probably copied from the pokesnipers code.  I don't think it is necessary here (I did double-check that this was the case for Farfetched). I also checked code in the POGO Location Feeder project and did not see this modification.

Fix pokewatchers sniping, which was not respecting the 1 req. every 5 seconds

---

PoGo.NecroBot.CLI/Config/Translations/translation.ja-JP2.json

Convert the double-byte symbol to 1 byte katakana.

FIX translation.ja-JP2.json

---

PoGo.NecroBot.ConfigUI/MainWindow.xaml
PoGo.NecroBot.ConfigUI/Models/ObservableSettings.cs
PoGo.NecroBot.ConfigUI/PoGo.NecroBot.ConfigUI.csproj

Fixes for UI and build configs

Fixes for UI and build

---

PoGo.NecroBot.CLI/ConsoleEventListener.cs

Fix AmountOfPokemonToDisplayOnStart = 0 still print headers
#5265

Fix AmountOfPokemonToDisplayOnStart = 0 headers

---

PoGo.NecroBot.Logic/ILogicSettings.cs
PoGo.NecroBot.Logic/Settings.cs
PoGo.NecroBot.Logic/Tasks/FarmPokestopsTask.cs

Randomly stops at pokestops and waits for random time to make more human like

Have random wait times at pokestops

---

PoGo.NecroBot.CLI/ConsoleEventListener.cs
PoGo.NecroBot.Logic/StatisticsAggregator.cs
PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

So many exception message floating in the diagnosis and output windows of visual studio....from the event and stataisticAggregator.....

Fix event exception

---

PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs

The bug is hided in a congested logic to determine if the locations from the web to be used to snipe. This fix separate it to easy to read logic and echo a message to user. ( user don't know which source (pokesniper or poke watcher or skipplagged ) is reliable and which source suit their need, so it is better let them know the actual filtering process.....For example, user use both pokesniper and pokewatcher may find the results from poke sniper is more than poke watcher but actually, it is because user called the pokesniper function first before pokewatcher, so most pokemon in pokewatcher is already visited during the pokesniper scan operation. With a status added to the filter process, user can know why they can't get any result from a certain source. 
Another example is, if the user …

fixed snipe bug of going to already expired pokemon location

---

PoGo.NecroBot.CLI/Config/Translations/translation.ja-JP.json

FIX to avoid the display bug.
And replacing the JP and JP2 because there is a need to change the default language file.

FIX translation.ja-JP.json

---

PoGo.NecroBot.CLI/Config/Translations/translation.cs.json

https://github.com/NECROBOTIO/NecroBot/issues/5340

Removed * at beginning line 0, position 0 #5340
